### ISSUE TITLE
We downloaded XML files but we need text files.

### ISSUE THREAD

**Issue by egepelindag** [egepelindag/CE216-PROJECT-TEAM13#4]

**Comment by Cobnn2** [comment]
In order to get text files, we decided to parse the xml files. We started by smaller sized xml files as they were easier to read because of their structure was not too complicated.  We used DOM to parse smaller sized files. Unfortunately DOM did not work with the two files called ""eng-deu" and "deu-eng". We ended up using SAX parser for them to get text files. SAX parser worked well for us, so we had clean text files in the format that we want.
